import {
  Activity,
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  ArrowUpDown,
  BarChart3,
  Bell,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  CreditCard,
  DollarSign,
  Eye,
  FileText,
  Filter,
  Home,
  Info,
  LogOut,
  Moon,
  MoreVertical,
  Plus,
  Save,
  Search,
  Settings,
  Shield,
  Stethoscope,
  StopCircle,
  Sun,
  TrendingUp,
  User,
  UserCheck,
  Users,
  X,
  XCircle,
  ClipboardList,
  Play,
  Upload,
  Download,
  Mail,
  Phone,
  MapPin,
  Pencil,
  Trash2,
  RefreshCcw,
  Copy,
  ExternalLink,
  Lock,
  TriangleAlert,
  Star,
  HeartPulse,
  Pill,
  Hospital,
  ReceiptText,
  BadgeCheck,
  Circle,
} from "lucide-react";

const ICONS = {
  activity: Activity,
  alertCircle: AlertCircle,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUpDown: ArrowUpDown,
  barChart2: BarChart3,
  bell: Bell,
  calendar: Calendar,
  check: Check,
  checkCircle: CheckCircle2,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  clock: Clock,
  creditCard: CreditCard,
  dollarSign: DollarSign,
  eye: Eye,
  fileText: FileText,
  filter: Filter,
  home: Home,
  info: Info,
  logOut: LogOut,
  moon: Moon,
  moreVertical: MoreVertical,
  plus: Plus,
  save: Save,
  search: Search,
  settings: Settings,
  shield: Shield,
  stethoscope: Stethoscope,
  stopCircle: StopCircle,
  sun: Sun,
  trendingUp: TrendingUp,
  user: User,
  userCheck: UserCheck,
  users: Users,
  x: X,
  xCircle: XCircle,
  clipboardList: ClipboardList,
  play: Play,
  upload: Upload,
  download: Download,
  mail: Mail,
  phone: Phone,
  location: MapPin,
  edit: Pencil,
  trash: Trash2,
  refresh: RefreshCcw,
  copy: Copy,
  externalLink: ExternalLink,
  lock: Lock,
  warning: TriangleAlert,
  star: Star,
  heartPulse: HeartPulse,
  pill: Pill,
  hospital: Hospital,
  receipt: ReceiptText,
  verified: BadgeCheck,
  pending: Clock,
  circle: Circle,
};

export default function Ico({ n, size = 18, color = "currentColor", className, style }) {
  const Icon = ICONS[n] || Activity;
  return <Icon size={size} color={color} className={className} style={style} />;
}

